"""add task recurrence interval days

Revision ID: 02d8ef033834
Revises: b3a596e050ba
Create Date: 2026-09-05 17:27:26.502042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d8ef033834'
down_revision: Union[str, None] = 'b3a596e050ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('recurrence_interval_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'recurrence_interval_days')
    # ### end Alembic commands ###
