"""add shift patterns and meal categories

Revision ID: 0df84fd674ed
Revises: cce9eef9e5b1
Create Date: 2026-09-04 23:32:49.223310

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df84fd674ed'
down_revision: Union[str, None] = 'cce9eef9e5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

MEAL_CATEGORIES = ["Staff Meals", "Gastro", "Events", "Traiteurs", "Office Meals", "À la Carte", "Other"]
# Seeded with the two time ranges already in use in existing shift data
# (06:00-14:00, 07:00-15:00) plus a sensible spread of common patterns, so no
# staff member's existing assignment goes unmatched by the new dropdown.
SHIFT_PATTERNS = [
    "06:00-14:00", "07:00-15:00", "08:00-16:00", "14:00-22:00", "15:00-23:00", "22:00-06:00", "Off",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    meal_categories = op.create_table('meal_categories',
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    shift_patterns = op.create_table('shift_patterns',
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    # ### end Alembic commands ###

    op.bulk_insert(meal_categories, [{"id": uuid.uuid4(), "label": label} for label in MEAL_CATEGORIES])
    op.bulk_insert(shift_patterns, [{"id": uuid.uuid4(), "label": label} for label in SHIFT_PATTERNS])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_patterns')
    op.drop_table('meal_categories')
    # ### end Alembic commands ###
