"""add area types

Revision ID: 337fa3207deb
Revises: 0df84fd674ed
Create Date: 2026-09-05 13:51:03.989575

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337fa3207deb'
down_revision: Union[str, None] = '0df84fd674ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

AREA_TYPES = ["Bedrooms", "Guest Rooms", "Kitchen", "Living Areas", "Bathrooms", "Office", "Outdoor", "Utility", "Other"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    area_types = op.create_table('area_types',
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    # ### end Alembic commands ###

    op.bulk_insert(area_types, [{"id": uuid.uuid4(), "label": label} for label in AREA_TYPES])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('area_types')
    # ### end Alembic commands ###
