"""add weekly staff meal plans

Revision ID: 6d3cfcc06bd9
Revises: 8047a1441b96
Create Date: 2026-09-04 22:33:33.253121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3cfcc06bd9'
down_revision: Union[str, None] = '8047a1441b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_meal_plans',
    sa.Column('occasion_type', sa.String(length=60), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_meal_plan_entries',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.String(length=3), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=True),
    sa.Column('custom_meal_name', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['weekly_meal_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_meal_plan_entries')
    op.drop_table('weekly_meal_plans')
    # ### end Alembic commands ###
