"""add stock transfers for raw material logging

Revision ID: 8047a1441b96
Revises: a2523ee14474
Create Date: 2026-09-04 22:08:54.921179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8047a1441b96'
down_revision: Union[str, None] = 'a2523ee14474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_transfers',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('logged_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_transfer_lines',
    sa.Column('transfer_id', sa.Uuid(), nullable=False),
    sa.Column('food_inventory_id', sa.Uuid(), nullable=True),
    sa.Column('ingredient_name', sa.String(length=150), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['food_inventory_id'], ['food_inventory.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_transfer_lines')
    op.drop_table('stock_transfers')
    # ### end Alembic commands ###
