"""add task start_time and end_time

Revision ID: 98c8af58bf04
Revises: 9b3f38a94eec
Create Date: 2026-09-04 20:20:05.475038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c8af58bf04'
down_revision: Union[str, None] = '9b3f38a94eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('tasks', sa.Column('end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'end_time')
    op.drop_column('tasks', 'start_time')
    # ### end Alembic commands ###
