"""add staff supervisor_id

Revision ID: a2523ee14474
Revises: 98c8af58bf04
Create Date: 2026-09-04 21:26:12.905176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2523ee14474'
down_revision: Union[str, None] = '98c8af58bf04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_profiles', sa.Column('supervisor_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'staff_profiles', 'staff_profiles', ['supervisor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff_profiles', type_='foreignkey')
    op.drop_column('staff_profiles', 'supervisor_id')
    # ### end Alembic commands ###
