"""add user notification prefs

Revision ID: b3a596e050ba
Revises: 337fa3207deb
Create Date: 2026-09-05 14:28:25.143208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3a596e050ba'
down_revision: Union[str, None] = '337fa3207deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('notification_prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_prefs')
    # ### end Alembic commands ###
