"""add recipe ingredient yield_pct

Revision ID: cce9eef9e5b1
Revises: 6d3cfcc06bd9
Create Date: 2026-09-04 22:41:53.191299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce9eef9e5b1'
down_revision: Union[str, None] = '6d3cfcc06bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'recipe_ingredients',
        sa.Column('yield_pct', sa.Numeric(precision=5, scale=2), nullable=False, server_default='100'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredients', 'yield_pct')
    # ### end Alembic commands ###
